---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-niginx-prctice
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/iam-manibabu-karnam/flux-niginx-prctice.git
